datasources:
  default:
    # Perfil alternativo para correr sin Docker (solo local/rapido).
    url: jdbc:h2:file:./data/toursdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    schema-generate: CREATE_DROP
    dialect: H2
